-- liquibase formatted sql

-- changeset panch:1753740612920-1
CREATE TABLE conversation_members
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    conversation_id BIGINT                                  NOT NULL,
    user_id         BIGINT                                  NOT NULL,
    last_read_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_conversation_members PRIMARY KEY (id)
);

-- changeset panch:1753740612920-2
CREATE TABLE conversations
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type VARCHAR(255)                            NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_conversations PRIMARY KEY (id)
);

-- changeset panch:1753740612920-3
CREATE TABLE messages
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    conversation_id BIGINT                                  NOT NULL,
    sender_id       BIGINT                                  NOT NULL,
    content         TEXT                                    NOT NULL,
    type            VARCHAR(255),
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_messages PRIMARY KEY (id)
);

-- changeset panch:1753740612920-4
CREATE TABLE role
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    external_id VARCHAR(255)                            NOT NULL,
    is_active   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_role PRIMARY KEY (id)
);

-- changeset panch:1753740612920-5
CREATE TABLE users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name  VARCHAR(255)                            NOT NULL,
    last_name   VARCHAR(255)                            NOT NULL,
    username    VARCHAR(255)                            NOT NULL,
    email       VARCHAR(255)                            NOT NULL,
    keycloak_id VARCHAR(255)                            NOT NULL,
    avatar_url  VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    role_id     BIGINT,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- changeset panch:1753740612920-6
ALTER TABLE role
    ADD CONSTRAINT uc_role_external UNIQUE (external_id);

-- changeset panch:1753740612920-7
ALTER TABLE role
    ADD CONSTRAINT uc_role_name UNIQUE (name);

-- changeset panch:1753740612920-8
ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

-- changeset panch:1753740612920-9
ALTER TABLE users
    ADD CONSTRAINT uc_users_keycloak UNIQUE (keycloak_id);

-- changeset panch:1753740612920-10
ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

-- changeset panch:1753740612920-11
ALTER TABLE conversation_members
    ADD CONSTRAINT FK_CONVERSATION_MEMBERS_ON_CONVERSATION FOREIGN KEY (conversation_id) REFERENCES conversations (id);

-- changeset panch:1753740612920-12
ALTER TABLE conversation_members
    ADD CONSTRAINT FK_CONVERSATION_MEMBERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

-- changeset panch:1753740612920-13
ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGES_ON_CONVERSATION FOREIGN KEY (conversation_id) REFERENCES conversations (id);

-- changeset panch:1753740612920-14
ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGES_ON_SENDER FOREIGN KEY (sender_id) REFERENCES users (id);

-- changeset panch:1753740612920-15
ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ROLE FOREIGN KEY (role_id) REFERENCES role (id);

